### ISSUE TITLE
Request.files is empty

### ISSUE THREAD

**Issue by ShraddhaKesharwani** [askrella/speech-rest-api#7]
Hello,

This is with regards to speech to text using whisper.
We are trying to bring rest api in place and on running the below command we see the request.files is not reading our audio=audiofile.wav.
curl -X POST   -F "audio=audiofile.wav"   http://localhost:3000/transcribe

The audiofile.wav is not received by the service; request.files is empty : ImmutableMultiDict([])
Could you please advise what can be done?

Thanks and regards,
Shraddha

**Comment by navopw** [comment]
Can you try this command?

```
curl --location ‘http://localhost:3000/transcribe’ --form ‘audio=@“/Users/stanislav/Downloads/test.mp3”’
```

Replace `/Users/stanislav/...` with your path to your audio file.

**Comment by ShraddhaKesharwani** [comment]
Hi,
Yes this worked.
Thank you so much for quick resolution. :)

Regards,
Shraddha
